# Generated by Django 5.2.17 on 2026-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboard',
                'managed': False,
            },
        ),
    ]
