# Generated by Django 5.2.17 on 2026-10-01 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_total_is_subtotal_plus_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='max_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The most days delivery takes (the same as the fewest for 'in 2 days').", null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='min_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The fewest days delivery takes. Empty: no estimate shown.', null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='deliverycharge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_days__isnull', True), ('min_days__isnull', True)), models.Q(('max_days__isnull', False), ('min_days__isnull', False), ('min_days__lte', models.F('max_days'))), _connector='OR'), name='deliverycharge_days_both_or_neither_in_order', violation_error_message='Give both the fewest and the most days (the most may not be less), or leave both empty.'),
        ),
    ]
