# Generated by Django 5.2.17 on 2026-10-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequestKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=40)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_keys', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'owner'), name='orderrequestkey_one_per_key_and_owner')],
            },
        ),
    ]
