# Generated by Django 5.2.17 on 2026-09-23 18:51

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.RandomUploadTo('profile_pictures'), validators=[apps.core.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-50 characters: letters, digits, dot, dash or underscore.', regex='^[A-Za-z0-9_.-]{3,50}$')]),
        ),
    ]
