# Generated by Django 5.2.17 on 2026-10-04 19:02

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_delivery_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('received', 'Received'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('damaged', 'It arrived damaged'), ('wrong_item', 'I got the wrong item'), ('not_as_described', 'It is not as described'), ('size_fit', 'The size or fit is wrong'), ('changed_mind', 'I changed my mind'), ('other', 'Something else')], max_length=30)),
                ('details', models.CharField(blank=True, help_text="What the customer wrote (required for 'Something else').", max_length=500)),
                ('response', models.CharField(blank=True, help_text='Your message to the customer, shown on their order: how to send the goods back, or why it was refused.', max_length=500)),
                ('goods_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The price of the returned lines, less their share of the order's coupon.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('courier_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="What the courier charges to carry the goods back (the order's delivery charge).", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the customer pays of the courier cost, taken off the refund. 0 = free return: the shop pays the courier (that comes out of its profit). Worked out from the policy when the request is made; change it to waive it.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='What is paid back: the goods less the return charge. Changes by itself when you change the charge; type another figure to pay back more or less.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Units the customer asked to return.', validators=[django.core.validators.MinValueValidator(1)])),
                ('good_quantity', models.PositiveIntegerField(default=0, help_text='Units that came back fine: back on the shelf.')),
                ('damaged_quantity', models.PositiveIntegerField(default=0, help_text='Units that came back damaged: not sellable, only counted.')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.orderitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Untick to stop taking new return requests (existing ones stay).')),
                ('window_days', models.PositiveSmallIntegerField(default=7, help_text='How many days after delivery a customer may ask to return something.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('charge_return_delivery', models.BooleanField(default=True, help_text='The customer pays the delivery charge of sending the goods back (it is taken off the refund), unless the shop was at fault: damaged, wrong item, not as described. Untick and every return is free; the shop pays the courier. Staff can still waive the charge of one request.')),
            ],
            options={
                'verbose_name': 'return settings',
                'verbose_name_plural': 'return settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='returns_one_settings_row')],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='returnreq_status_newest_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('goods_amount__gte', 0)), name='returnreq_goods_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('courier_cost__gte', 0)), name='returnreq_courier_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('return_charge__gte', 0)), name='returnreq_return_charge_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='returnreq_refund_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='returnitem_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('good_quantity'), '+', models.F('damaged_quantity')))), name='returnitem_received_not_more_than_asked'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.UniqueConstraint(fields=('request', 'order_item'), name='returnitem_one_line_once_per_request'),
        ),
    ]
