# Generated by Django 5.2.17 on 2026-09-24 08:48

import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Home'), ('newarrival', 'New arrivals'), ('flashsale', 'Flash sale'), ('best_selling', 'Best selling'), ('feature', 'Featured'), ('category', 'Categories')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'page content',
                'verbose_name_plural': 'page content',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('image_slider', 'Image slider'), ('video_slider', 'Video slider'), ('left_banner', 'Left banner'), ('right_banner', 'Right banner')], help_text='A page has at most one active left banner and one active right banner.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first.')),
                ('link_type', models.CharField(choices=[('product', 'A product'), ('category', 'A category'), ('external', 'Another website')], default='product', max_length=10)),
                ('external_link', models.CharField(blank=True, help_text='Starts with https://', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('media', models.FileField(help_text='Slider and left banner: an image. Video slider: a video. Right banner: either.', upload_to=apps.core.uploads.RandomUploadTo('content'), validators=[apps.core.validators.validate_media_upload])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], editable=False, max_length=10)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide it without deleting it.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.pagecontent')),
            ],
            options={
                'ordering': ['page', 'placement', 'order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('placement__in', ('left_banner', 'right_banner'))), fields=('page', 'placement'), name='content_one_active_banner_per_side', violation_error_message='This page already has an active banner on that side.'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('external_link', ''), ('link_type', 'product'), ('product__isnull', False)), models.Q(('category__isnull', False), ('external_link', ''), ('link_type', 'category'), ('product__isnull', True)), models.Q(('category__isnull', True), ('link_type', 'external'), ('product__isnull', True), models.Q(('external_link', ''), _negated=True)), _connector='OR'), name='content_link_matches_type', violation_error_message='The link does not match its type.')],
            },
        ),
    ]
