# Generated by Django 5.2.17 on 2026-10-01 19:00

import apps.core.uploads
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_flash_sale'),
        ('content', '0002_create_pages'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentitem',
            name='content_one_active_banner_per_side',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='cta_label',
            field=models.CharField(blank=True, default='Shop Now', help_text='The words on the button over a slide or the mid-page banner ("Shop Now", "See the deals"). Leave it empty for no button.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='media',
            field=models.FileField(help_text='Slider, left banner and mid-page banner: an image. Video slider: a video. Right banner: either.', upload_to=apps.core.uploads.RandomUploadTo('content'), validators=[apps.core.validators.validate_media_upload]),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='placement',
            field=models.CharField(choices=[('image_slider', 'Image slider'), ('video_slider', 'Video slider'), ('left_banner', 'Left banner'), ('right_banner', 'Right banner'), ('mid_banner', 'Mid-page banner')], help_text='A page has at most one active left banner, one active right banner and one active mid-page banner (the Home page only).', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('placement__in', ('left_banner', 'right_banner', 'mid_banner'))), fields=('page', 'placement'), name='content_one_active_banner_per_side', violation_error_message='This page already has an active banner on that side.'),
        ),
    ]
