# Generated by Django 5.2.17 on 2026-09-28 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='What the customer types. Stored upper case.', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, help_text='Staff-only note; never shown to a customer.', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='A percentage (0-100) or a fixed amount, depending on the type above.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The subtotal must be at least this. Empty: no minimum.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps how much is taken off, however big the order. Empty: no cap.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total uses allowed. Empty: unlimited.', null=True)),
                ('max_redemptions_per_customer', models.PositiveIntegerField(blank=True, help_text='Uses allowed per phone number. Empty: unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, help_text="Moved only by code, like a product's order count.")),
                ('valid_from', models.DateTimeField(blank=True, help_text='Empty: usable from the moment it is saved.', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Empty: never expires on its own.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to turn it off immediately, without waiting for an expiry date.')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='coupon_discount_value_gt_0'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('discount_value__lte', 100), _connector='OR'), name='coupon_percentage_value_lte_100'), models.CheckConstraint(condition=models.Q(('min_order_amount__isnull', True), ('min_order_amount__gte', 0), _connector='OR'), name='coupon_min_order_amount_gte_0'), models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gt', 0), _connector='OR'), name='coupon_max_discount_amount_gt_0'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='coupon_valid_until_after_valid_from')],
            },
        ),
    ]
