# Generated by Django 5.2.17 on 2026-09-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='public_title',
            field=models.CharField(blank=True, help_text='What the customer reads on the offer, e.g. "25% off your first order". Needed to show the coupon at checkout.', max_length=60),
        ),
        migrations.AddField(
            model_name='coupon',
            name='show_at_checkout',
            field=models.BooleanField(default=False, help_text='Suggest this coupon to customers at checkout, so they do not need to know the code. Leave it off for secret codes (influencers, a sorry-for-the-delay code): it still works when typed.'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('show_at_checkout', False), models.Q(('public_title', ''), _negated=True), _connector='OR'), name='coupon_shown_at_checkout_needs_a_title', violation_error_message='Write the title customers will see before showing this coupon at checkout.'),
        ),
    ]
