# Generated by Django 5.2.17 on 2026-09-24 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_default_delivery_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cod', 'Cash on delivery')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payment_status_newest_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_gte_0'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid'])), fields=('order',), name='payment_one_live_per_order'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['paid', 'refunded']), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payment_collected_has_paid_at'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'refunded'), _negated=True), ('refunded_at__isnull', False), _connector='OR'), name='payment_refunded_has_refunded_at')],
            },
        ),
    ]
