# Generated by Django 5.2.17 on 2026-09-24 19:00

import apps.core.uploads
import apps.core.validators
import apps.siteconfig.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once someone has answered it.')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Groups the questions (Orders, Shipping, ...). Empty: General.', max_length=60)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Plain text; a new line stays a new line.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide it without deleting it.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The address of the page: /pages/<slug>. Lower case, digits and dashes.', max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='HTML: headings (h2, h3), paragraphs, lists, links, images, tables. Scripts and styles are removed when you save.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to take the page offline without deleting it.')),
                ('footer_group', models.CharField(blank=True, choices=[('', 'Not in the footer'), ('company', 'Company'), ('service', 'Customer service'), ('legal', 'Legal (bottom row)')], default='', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first (in the footer).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop sending to this address.')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at', '-id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='siteconfig_subscriber_email_unique')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Shop', help_text='Shown in the header, the footer and the browser tab.', max_length=60)),
                ('tagline', models.CharField(blank=True, help_text='One short line under the name in the browser tab (optional).', max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='JPEG, PNG or WebP, square works best. Empty: the logo that ships with the storefront.', upload_to=apps.core.uploads.RandomUploadTo('site'), validators=[apps.core.validators.validate_image_upload])),
                ('announcement_enabled', models.BooleanField(default=False, help_text='Show the bar above the header.')),
                ('announcement_text', models.CharField(blank=True, max_length=200)),
                ('announcement_link', models.CharField(blank=True, help_text='A page of this shop (/products/flash-sale) or another website (https://...). Empty: plain text.', max_length=300, validators=[apps.siteconfig.validators.validate_link])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=250)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. Sat - Thu: 10:00 AM - 8:00 PM', max_length=120)),
                ('map_embed_url', models.CharField(blank=True, help_text='The src address of an embedded map (Google Maps > Share > Embed a map). Empty: no map on the contact page.', max_length=1000, validators=[apps.siteconfig.validators.validate_map_embed])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='siteconfig_one_settings_row')],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X (Twitter)'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20)),
                ('url', models.CharField(help_text='Starts with https://', max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide it without deleting it.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='siteconfig.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('site', 'platform'), name='siteconfig_one_link_per_platform', violation_error_message='This platform is already listed.')],
            },
        ),
    ]
