# Generated by Django 5.2.17 on 2026-09-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('delivery', 'Delivery'), ('returns', 'Returns'), ('secure_payment', 'Secure payment'), ('cash_on_delivery', 'Cash on delivery'), ('support', 'Support'), ('warranty', 'Warranty')], max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide it without deleting it.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_badges', to='siteconfig.sitesettings')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
