# Generated by Django 5.2.17 on 2026-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_trustbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_ends_at',
            field=models.DateTimeField(blank=True, help_text='Show the bar until this moment, then hide it by itself (e.g. when a sale ends). Empty: until you switch it off.', null=True),
        ),
    ]
