# Generated by Django 5.2.17 on 2026-09-24 06:35

import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to generate it from the name.', max_length=110, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='brand_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to generate it from the name.', max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.core.uploads.RandomUploadTo('categories'), validators=[apps.core.validators.validate_image_upload])),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(help_text='For example #FF0000.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Use a hex colour such as #FF0000.')])),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='color_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to generate it from the name.', max_length=280, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('short_description', models.TextField(blank=True, help_text='Rich text. HTML is cleaned when saved.')),
                ('long_description', models.TextField(blank=True, help_text='Rich text. HTML is cleaned when saved.')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('weight', models.CharField(blank=True, help_text='Shown as typed, e.g. "500 g".', max_length=50)),
                ('dimension_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dimension_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dimension_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(blank=True, max_length=150)),
                ('features', models.TextField(blank=True)),
                ('warranty_information', models.TextField(blank=True)),
                ('shipping_information', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from the shop.')),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_views', models.PositiveIntegerField(default=0, editable=False)),
                ('total_orders', models.PositiveIntegerField(default=0, editable=False)),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('qrcode_image', models.ImageField(blank=True, editable=False, upload_to=apps.core.uploads.RandomUploadTo('qrcodes'))),
                ('qrcode_target', models.CharField(blank=True, editable=False, max_length=500)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
                ('primary_category', models.ForeignKey(blank=True, help_text="The category used for 'related products'. It is added to the categories above automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.core.uploads.RandomUploadTo('products'), validators=[apps.core.validators.validate_media_upload])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], editable=False, max_length=10)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.core.uploads.RandomUploadTo('products/thumbs'), validators=[apps.core.validators.validate_image_upload])),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first. The first image is the main image.')),
                ('color', models.ForeignKey(blank=True, help_text='Leave empty for media that belongs to the whole product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product media',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers first (S=1, M=2, L=3, ...).')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='size_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, help_text='Leave empty to derive it from the product SKU.', max_length=100, unique=True, verbose_name='SKU')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text="Empty = the product's price.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text="Final price of this variant. Empty = apply the product's discount.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='The variant the shop picks when none is chosen.')),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='tag_name_unique_ci')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='category_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('discount_amount__lte', 100), _connector='OR'), name='category_percentage_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', 0), models.Q(('discount_type', ''), _negated=True), _connector='OR'), name='category_discount_has_type'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='variant_unique_color_size', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='variant_one_default_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), ('base_price__isnull', True), ('discount_price__lte', models.F('base_price')), _connector='OR'), name='variant_discount_price_lte_base_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='product_active_newest_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='product_base_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='product_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('discount_value__lte', 100), _connector='OR'), name='product_percentage_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'fixed'), _negated=True), ('discount_value__lte', models.F('base_price')), _connector='OR'), name='product_fixed_lte_base_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value', 0), models.Q(('discount_type', ''), _negated=True), _connector='OR'), name='product_discount_has_type'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_quantity__gte', 1)), name='product_moq_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('avg_rating__gte', 0), ('avg_rating__lte', 5)), name='product_rating_0_to_5'),
        ),
    ]
