# Generated by Django 5.2.17 on 2026-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(blank=True, help_text='The sale shows from this moment. Empty: it is already running.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='The sale stops showing at this moment, and the shop counts down to it. Empty: no deadline.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'flash sale',
                'verbose_name_plural': 'flash sale',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='catalog_one_flash_sale_row'), models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='catalog_flash_sale_ends_after_it_starts', violation_error_message='The end must be after the start.')],
            },
        ),
    ]
