# Generated by Django 5.2.17 on 2026-10-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
