# Generated by Django 5.2.17 on 2026-10-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_variant_damaged_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('name', models.CharField(help_text='The product and variant as they were named then.', max_length=255)),
                ('kind', models.CharField(choices=[('sale', 'Sold'), ('restock', 'Order put back'), ('return', 'Returned goods received'), ('manual', 'Changed by hand')], max_length=10)),
                ('change', models.IntegerField(help_text='Units added to (+) or taken from (-) the stock. 0 when only damaged units came back.')),
                ('damaged_change', models.PositiveIntegerField(default=0, help_text='Units that came back damaged: counted, never added to the stock.')),
                ('stock_after', models.PositiveIntegerField(help_text='What was in stock after this line.')),
                ('reference', models.CharField(blank=True, help_text='The order number, or the return request.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='stockmove_variant_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('change', 0), _negated=True), ('damaged_change__gt', 0), _connector='OR'), name='stockmove_moves_something')],
            },
        ),
    ]
