# Generated by Django 5.2.17 on 2026-10-09 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stock_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_when_left', models.PositiveSmallIntegerField(default=5, help_text='Show "Only N left" when 1 to this many units are in stock (the real number, so customers hurry). 0 switches it off.', validators=[django.core.validators.MaxValueValidator(1000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stock notice',
                'verbose_name_plural': 'stock notice',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='catalog_one_stock_notice_row')],
            },
        ),
    ]
