# Generated by Django 5.2.17 on 2026-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Show this review on the shop's homepage. Tick the ones you want: only those are shown (up to 8). With none ticked, the shop picks good ones itself (4-5 stars, a real comment, a delivered purchase)."),
        ),
    ]
