# Generated by Django 5.2.17 on 2026-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_placed', models.BooleanField(default=True, help_text='An order was placed.')),
                ('notify_on_confirmed', models.BooleanField(default=True, help_text='Staff confirmed the order.')),
                ('notify_on_shipped', models.BooleanField(default=True, help_text='The order was shipped.')),
                ('notify_on_delivered', models.BooleanField(default=True, help_text='The order was delivered (e-mail only).')),
                ('notify_on_cancelled', models.BooleanField(default=True, help_text='The order was cancelled.')),
                ('notify_on_refunded', models.BooleanField(default=True, help_text='The order was refunded.')),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='notifications_one_settings_row')],
            },
        ),
    ]
